spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: rahasia
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update